### ISSUE TITLE
Incorrect API specification for "TextureParameterName" and "TextureTarget"

### ISSUE THREAD

**Issue by frabert** [KhronosGroup/OpenGL-API#1]
Some values, like `GL_TEXTURE_MAX_LEVEL`, should be inside the `TextureParameterName` group, and not inside the `TextureTarget` group.

See luca-piccioni/OpenGL.Net#38 for an example of incorrect behavior caused by this.

**Comment by oddhack** [comment]
Please move this over to the OpenGL-Registry  repository where gl.xml is kept - you have some other issues/PRs over there so maybe this is just left over from earlier?
