### ISSUE TITLE
GL 4.6: GL_PARAMETER_BUFFER and memory barriers

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-API#17]
ARB_indirect_parameters (and the equivalent GL 4.6 specification) does not define a `glMemoryBarrier` bit that allows writes from image load/store and SSBOs to be visible to parameter buffer reads. And none of the existing barriers are stated to provide this functionality.

So at present, it seems impossible to use image load/store or SSBOs to write indirect parameters. Only atomic counters can write to them from shaders, [assuming that is the intent of the atomic counter feature](https://github.com/KhronosGroup/OpenGL-API/issues/14).

**Comment by nhaehnle** [comment]
This only affects the drawcount. COMMAND_BUFFER_BARRIER_BIT should be extended to mention MultiDraw*IndirectCount.

While we're at it, the type of the maxdrawcount of MultiDrawArraysIndirectCount should be sizei (like MultiDrawElementsIndirectCount).

**Comment by NicolBolas** [comment]
I assume you mean `GL_COMMAND_BARRIER_BIT`.

**Comment by nhaehnle** [comment]
Yeah, obviously :)

**Comment by pdaniell-nv** [comment]
Discussed in the WG meeting today. We agree with Nicolai's suggestion. @nhaehnle can you make a proposed spec change here for Jon to incorporate? Thanks.

**Comment by nhaehnle** [comment]
Also sent a pull request for the spec internally. Not sure if that's the best procedure, but it's only a handful of words that change...

https://gitlab.khronos.org/opengl/API/merge_requests/4

**Comment by oddhack** [comment]
This will be fixed in the next public spec update.

**Comment by oddhack** [comment]
(Coming soon).
