### ISSUE TITLE
GL 4.6: core spec mentions fixed-function lighting in text.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-API#18]
See this quote from page 475:

>  Note that these modes affect only the final rasterization of polygons: in particular, **a polygon’s vertices are lit**, and the polygon is clipped and possibly culled before these modes are applied.

Emphasis added. The core profile specification should probably not have that clause.

**Comment by pdaniell-nv** [comment]
Perhaps we should change that sentence on page 475 with this:

> Note that these modes affect only the final rasterization of polygons: in particular, vertex processing, polygon clipping and possibly polygon culling happen before these modes are applied.

**Comment by oddhack** [comment]
It's also straightforward to conditionalize the clause so it doesn't show up in core profile.

**Comment by pdaniell-nv** [comment]
Approved either way to address the issue in the OpenGL|ES meeting. Up to @oddhack as editor to choose. Assigned to update spec.

**Comment by oddhack** [comment]
This will be fixed in the next spec update, coming soon.
