### ISSUE TITLE
EXT_window_rectangles extension specification update

### ISSUE THREAD

**Issue by markkilgard** [KhronosGroup/OpenGL-API#21]
I've updated the EXT_window_rectangles specification (attached) to fix an issue noted by Kai Ninomiya @ Google and added an issue 29 about Vulkan support.

Please update the registry version with the attached version.  Thanks.

[EXT_window_rectangles.txt](https://github.com/KhronosGroup/OpenGL-API/files/1441766/EXT_window_rectangles.txt)

**Comment by markkilgard** [comment]
(FYI: this extension specification is for both ES and OpenGL)

**Comment by oddhack** [comment]
Please propose it as a pull request (with updates to xml/gl.xml, if there are any API changes) rather than an issue. Then we can iterate if needed, and just accept the PR from your branch.

**Comment by nvpbrown** [comment]
I am syncing NVIDIA's internal document repository with the Khronos repository and will create a pull request that contains the proposed edits.

**Comment by nvpbrown** [comment]
These edits are included in the following pull request:

https://github.com/KhronosGroup/OpenGL-Registry/pull/140

**Comment by dgkoch** [comment]
Closing PR was merged.
