### ISSUE TITLE
SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT has a min value of 256

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/OpenGL-API#22]
SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT declares a min. value of 256 in the spec (GL 4.4 p 589. table 23.64)

This seems like a bug to me:
- Min value for min. required UBO alignment is 1, I don't really see why SSBO would be different
- Vulkan spec declares a max. value of min. required SSBO alignment as 256
- Many drivers report values less than 256 for this value: http://opengl.gpuinfo.org/gl_stats_caps_single.php?listreportsbycap=GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT

It seems like either the spec should have a min. value of 1, or change the limit type to be max. value (and keep 256 to match Vulkan).

**Comment by nhaehnle** [comment]
This has been fixed in the GL 4.6 spec. There, table 23.64 has a footnote (dagger) on the 256 which clarifies that it's the maximum, not the minimum.
