### ISSUE TITLE
Errors in GL/GLES man pages

### ISSUE THREAD

**Issue by Richard-Yunchao** [KhronosGroup/OpenGL-API#25]
I am not sure whether this is the appropriate place to point out the errors in GL/GLES man page. If here is not the correct place, please let me know the correct one to discuss/revise such issues. 

One of the issues I found in gles man page:
The glGet variants in gles 3.1 man page at https://www.khronos.org/registry/OpenGL-Refpages/es3.1/html/glGet.xhtml miss some pnames as follows: 
SAMPLE_MASK_VALUE
MAX_DEPTH_TEXTURE_SAMPLES

A couple of some other issues are in GL/GLES man page, too. I would list them if here is the correct place to revise such issues. @pdaniell-nv

**Comment by oddhack** [comment]
Please post this over on https://github.com/KhronosGroup/OpenGL-Refpages/issues . Or if you want to post a pull request fixing the problems there, even better.
