### ISSUE TITLE
Bug in OpenGL ES 3.0 for TexImage2D

### ISSUE THREAD

**Issue by Richard-Yunchao** [KhronosGroup/OpenGL-API#26]
I am not sure whether you would fix bug in old specification like OpenGL ES 3.0. 

Here comes the bug:

Page 136 in GLES 3.0 spec (https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf): 
"If width, height, depth or levels is less than 1, the error INVALID_VALUE is generated. "
should be
"If width, height, depth or levels is less than 0, the error INVALID_VALUE is generated."

Just let you know in case you would fix bug in old specification.

**Comment by pdaniell-nv** [comment]
That line on page 136 of the OpenGL ES 3.0 spec is talking about TexStorage2D and and I believe "is less than 1" is correct since 0 would be an invalid texture size for creating an immutable texture.

For TexImage2D, the error is on page 133, and it says "less than 0" as you describe.

**Comment by Richard-Yunchao** [comment]
You are correct. It is in the section <Immutable-Format Texture Images>. It is not for TexImage2D/TexImage3D. I made a mistake here. Sorry for that. Close this issue then.
