### ISSUE TITLE
Bug in GLES 3.2 Spec: TexImage2DMultisample should be TexStorage2DMultisample

### ISSUE THREAD

**Issue by Richard-Yunchao** [KhronosGroup/OpenGL-API#27]
Page 182, in section 8.8 <Multisample Textures> in OpenGL ES 3.2 spec at https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf, the "TexImage2DMultisample" should be "TexStorage2DMultisample". 

In addition, I suppose that TexImage2DMultisample is not exposed in GLES 3.2. So the second "TexImage2DMultisample" at <Index> section on page 568 should be removed (I suppose this one is auto-generated from the one on page 182).

**Comment by pdaniell-nv** [comment]
Agreed this should say "TexStorage2DMultisample". Assigned to @oddhack to make the fix.

**Comment by oddhack** [comment]
This will be fixed in the next spec update, coming soon.
