### ISSUE TITLE
Bugs in GLES 3.0 for FramebufferTexture2D

### ISSUE THREAD

**Issue by Richard-Yunchao** [KhronosGroup/OpenGL-API#28]
(I am not sure whether you would fix the bug in GLES 3.0 spec. But I would like to point out the bugs. If you would never fix bugs in GLES 3.0 spec because it is too old or there are some other reasons, please let me know. Then I would not list the bugs I found) 

Section 4.4.2.4 in latest GLES 3.0 spec (GLES 3.0.5 at https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf), page 208, Errors for FramebufferTexture2D. There are 3 bugs: 
1) The sixth error statement "An INVALID_VALUE error is generated if texture is not zero and layer is larger than the value of MAX_3D_TEXTURE_SIZE minus one." should be removed.  This "Errors" section is specific for FramebufferTextuer2D, so there is no parameter "layer" at all. In addition, the text below to generate error for parameter "layer" for FramebufferTextureLayer has more details than this statement. 
2)  The seventh error statement "An INVALID_OPERATION error is generated if texture is not zero and textarget is not one of TEXTURE_2D, TEXTURE_2D_MULTISAMPLE, or one of the cube map face targets from table 3.21.". TEXTURE_2D_MULTISAMPLE should be removed. Because there is no multisample texture in GLES 3.0. AFAIK, multisample texture is supported in GLES 3.1.
3) The last statement "An INVALID_OPERATION error is generated if texture is the name of a buffer texture." should be removed. There is no buffer texture in GLES 3.0. AFAIK, buffer texture is supported in GLES 3.2.

**Comment by pdaniell-nv** [comment]
We typically don't update older specs. However, we will fix bugs in the latest OpenGL ES 3.2 spec if they still apply.
1. This bug is still in OpenGL ES 3.2.
2. This error is valid for OpenGL ES 3.2 so no change required.
3. This error is valid for OpenGL ES 3.2 so no change required.

@oddhack could you remove the irrelevant issue (1) from OpenGL ES 3.2.

**Comment by Richard-Yunchao** [comment]
Yes. The first bug exists in OpenGL ES 3.2 spec too.

**Comment by oddhack** [comment]
The first error will be fixed in the upcoming ES 3.2 spec update.
