### ISSUE TITLE
An issue about multisample texture in GLES 3.1 spec: the 3rd dimension for multisample texture is unnecessary

### ISSUE THREAD

**Issue by Richard-Yunchao** [KhronosGroup/OpenGL-API#29]
In GLES 3.1 spec (https://www.khronos.org/registry/OpenGL/specs/es/3.1/es_spec_3.1.pdf) at section 11.1.3.3 <Multisample Texture Fetches>, there is no 2D multisample texture array, so the multisample texture only have 2 dimensions. 

So in this statement below: 

the texel coordinates (i, j, k) refer to a texel outside the extents of the multisample texture image, where any of
             i < 0        i ≥ ws
             j < 0        j ≥ hs
             k < 0      k ≥ ds
and the size parameters ws, hs, and ds refer to the width, height, and depth of the image.

We should remove the depth dimension (all statement about 'k') , because we don't have 3D or 2D array multisample texture at all in GLES 3.1. 

WDYT?

**Comment by pdaniell-nv** [comment]
Yeah, it seems correct to remove the reference to depth for multisample textures. This issue is in the ES 3.2 spec.

**Comment by Richard-Yunchao** [comment]
In OpenGL ES 3.2, It has 2D array multisample texture (TexStorage3DMultisample). So it is OK to have 3rd dimension for texelFetch from multisample texture. 
But in OpenGL ES 3.1, it only has 2D multisample texture, so it is weird to have the 3rd dimension for textureFetch from multisample texture. 

However, you would not fix bugs in OpenGL ES 3.1, so you don't need to take action for this bug.

**Comment by pdaniell-nv** [comment]
Right, we're not planning to update the OpenGL ES 3.1 spec. Closing. Please reopen if you disagree. Thanks for reporting the issue.
