### ISSUE TITLE
Typos in OpenGL ES 3.2 SPEC

### ISSUE THREAD

**Issue by Jiawei-Shao** [KhronosGroup/OpenGL-API#31]
Hi,
I have found two typos in the latest OpenGL ES 3.2 SPEC:
(https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf)
1.  Chapter 11.3.1 Page 327, in the paragraph before "Points":
     A '.' is missed before "The input primitive type may be queried by calling GetProgramiv with pname GEOMETRY_INPUT_TYPE.".

2. Chapter 11.3.4.3 Page 331, in the second paragraph:
    There is a duplicated 'needs' in the first sentence "Similarly to the built-in inputs, each user-defined input has a value for each vertex and thus needs **needs** to be declared as arrays or inside input blocks declared as arrays".

**Comment by Jiawei-Shao** [comment]
@Richard-Yunchao

**Comment by Richard-Yunchao** [comment]
Good catch, Jiawei. I suppose that @pdaniell-nv and @oddhack would take another look and update the spec later.

**Comment by pdaniell-nv** [comment]
Agree both to both of these typos. Assigned to @oddhack to include in an upcoming spec.

**Comment by oddhack** [comment]
Fixed in the next ES spec update, coming soon.
