### ISSUE TITLE
Layout of compute shader shared variables

### ISSUE THREAD

**Issue by Jiawei-Shao** [KhronosGroup/OpenGL-API#40]
Hi,

Now OpenGL ES 3.2 SPEC does not define the layout of compute shader shared variables in the memory when validating GL_MAX_COMPUTE_SHARED_MEMORY_SIZE, will OpenGL(ES) SPEC define a default memory layout rule for compute shader shared variables like varying packing rules?

OpenGL Wiki mentions "OpenGL does not specify the exact mapping between GL types and shared variable storage, though you could use the std140 layout rules and UBO/SSBO sizes as a general guideline"[1], however in Mesa it seems the total memory of shared variables is computed though std430.

[1] https://www.khronos.org/opengl/wiki/Compute_Shader#Limitations
[2] https://cgit.freedesktop.org/mesa/mesa/tree/src/compiler/glsl/lower_shared_reference.cpp#n111

**Comment by Jiawei-Shao** [comment]
@qjia7

**Comment by pdaniell-nv** [comment]
Issue tracked internally here: https://gitlab.khronos.org/opengl/API/issues/88

**Comment by pdaniell-nv** [comment]
This issue was resolved in the latest OpenGL and OpenGL ES specs:
- https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf
  - section "19.1 Compute Shader Variables"
- https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf
  - section "17.1 Compute Shader Variables"
