### ISSUE TITLE
Typo in [OpenGL ES] GetUniformIndices() equivalent code

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-API#54]
Search for `GetUniformIndices` in OpenGL ES 3.2 Specification (February 2, 2019), hit 1/2:
Section 7.6. Uniform variables, page 105, second last code section is missing closing parenthesis before last semicolon.
`for (int i = 0; i < uniformCount; i++) {
uniformIndices[i] = GetProgramResourceIndex(program, UNIFORM, uniformNames[i];
}`
This issue does not appear in OpenGL 4.6 specification.

**Comment by pdaniell-nv** [comment]
Yeah, it would be nice to fix this. @oddhack could you fix this in your next API update. Thanks.

**Comment by oddhack** [comment]
Fixed in the 2019-10-22 spec updates.
