### ISSUE TITLE
MAX_SAMPLES listed in framebuffer dependent state table [OpenGL ES]

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-API#58]
In OpenGL ES 3.2, MAX_SAMPLES is listed in Table 21.56: Framebuffer Dependent Values.
MAX_SAMPLES should be listed in a table for implementation dependent values, ideally together with MAX_COLOR_TEXTURE_SAMPLES and others, like OpenGL 4.6 core does, Table 23.69: Implementation Dependent Values (cont.)

**Comment by pdaniell-nv** [comment]
Discussed in the OpenGL/ES meeting today. We agreed this is a bug and the fix to the OpenGL ES 3.2 spec is trivial. Assigned to @oddhack to make the change with the next OpenGL ES 3.2 spec update.

**Comment by oddhack** [comment]
Fixed in the 2019-10-22 spec updates.
