### ISSUE TITLE
OpenGL ES 3.1 minimum value for Max Fragment Uniform Vectors? [OpenGL ES]

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-API#59]
OpenGL ES Shading language 3.10 section 7.2 says gl_MaxFragmentUniformVectors has value of at least 224.
OpenGL ES 3.1 table 20.44 says MAX_FRAGMENT_UNIFORM_VECTORS has value of at least 256.
What is the minimum value?

**Comment by tsuoranta** [comment]
Same issue with max compute uniform components (GLSL ES 3.10 says 512, GL3.1 says 1024).

**Comment by pdaniell-nv** [comment]
Discussed in the OpenGL/ES meeting. We believe this is fixed in the latest OpenGL ES 3.2 and ESSL 3.2 specs. We don't plan to propagate the fix to the older specs.
