### ISSUE TITLE
OpenGL-Registry does not contain khrplatform.h

### ISSUE THREAD

**Issue by gshep** [KhronosGroup/OpenGL-API#6]
Currently the header can be found in EGL-Registry. Maybe it should be copied to the OpenGL-Registry repository too or extracted to the standalone repository?

**Comment by oddhack** [comment]
What is the "standalone repository"?

**Comment by gshep** [comment]
Sorry for confusing.

I meant to create new repository, for example 'KHR-Platform' and place the files there.

**Comment by oddhack** [comment]
khrplatform.h changes approximately never, since new platforms are rare. My only concern in making a copy is that it will be easy to forget to update it when never finally occurs. Don't want to create an entirely new repo for a single file.

**Comment by gshep** [comment]
Maybe it is worth to mention in README in OpenGL-Registry that the header could be found in the EGL-Registry?

I agree that copy-paste is a bad idea =)

**Comment by oddhack** [comment]
I added a comment to the repository README.adoc noting the requirement for khrplatform.h. There is already a similar comment in the index pages for the ES and SC registries, whose headers require khrplatform.h. Will that do?

**Comment by gshep** [comment]
Certainly!
