### ISSUE TITLE
Need WG signoff on OpenGL-Refpages pull 74

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenGL-API#61]
@pdaniell-nv @johnkslang please confirm https://github.com/KhronosGroup/OpenGL-Refpages/pull/74 fixes the corresponding issue. I'd have tagged you on that repo but the membership isn't setup to allow it.

**Comment by pdaniell-nv** [comment]
That fix looks good to me. Thanks.

**Comment by oddhack** [comment]
Merged.
