### ISSUE TITLE
Extension EXT_primitive_bounding_box name string has white space

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-API#64]
Originally filed to https://github.com/KhronosGroup/OpenGL-Registry/issues/372 but I suppose this is strictly speaking OpenGL-API issue.

```
Name

    EXT_primitive_bounding_box

Name Strings

    GL_EXT_primitive_bounding box
```

It is unexpected that there is space in the name string. I suppose this is just a typo, and `GL_EXT_primitive_bounding_box` is the intended name.

**Comment by pdaniell-nv** [comment]
Yes, definitely a typo. Will you propose a PR to fix it? Thanks.

**Comment by pdaniell-nv** [comment]
Oh never mind. I see this is addressed in https://github.com/KhronosGroup/OpenGL-Registry/issues/372. Closing.
