### ISSUE TITLE
BindVertexArray error language allows GenVertexArrays but not CreateVertexArrays

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-API#68]
OpenGL 4.6 (Core Profile, October 22, 2019) BindVertexArray error language says:

> An INVALID_OPERATION error is generated if array is not zero or a name returned from a previous call to GenVertexArrays, or if such a name has since been deleted with DeleteVertexArrays.

I propose:

An INVALID_OPERATION error is generated if array is not zero or a name returned from a previous call to _either GenVertexArrays or CreateVertexArrays_, or if such a name has since been deleted with DeleteVertexArrays.

**Comment by pdaniell-nv** [comment]
Sounds good. Assigned to @oddhack to incorporate into the next spec update.

**Comment by oddhack** [comment]
This should be fixed in the spec update of May 5, 2022.
