### ISSUE TITLE
DrawElementsInstanced, OpenGL 4.6 core, October 22, 2019 pdf

### ISSUE THREAD

**Issue by george-tsiros** [KhronosGroup/OpenGL-API#69]
pg 371:

> It is equivalent to
` 
DrawElementsInstancedBaseInstance(mode, count, type, indices,
instancecount, 0, 0);`

should read:

> It is equivalent to
` 
DrawElementsInstancedBaseInstance(mode, count, type, indices,
instancecount, 0);`

**Comment by oddhack** [comment]
Thanks! We'll fix this in the next spec update (which probably won't be in the near future, though).

**Comment by george-tsiros** [comment]
Since we're here, it would be _SO DAMN NICE_ if you made a non-trivial example for each of the draw call functions that demonstrated its usefulness.

**Comment by oddhack** [comment]
The original issue should be fixed in the spec update of May 5, 2022.
