### ISSUE TITLE
[OpenGL] Typo in glMapBufferRange spec

### ISSUE THREAD

**Issue by erik-kz** [KhronosGroup/OpenGL-API#70]
In the description of GL_MAP_PERSISTENT_BIT fashion is misspelled as fassion.

**Comment by pdaniell-nv** [comment]
What places misspell fashion as fassion? I looked in https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf but didn't see any occurrence of fassion.

**Comment by erik-kz** [comment]
My apologies, the typo was only in the refpages, not the spec PDF. I should have reported the issue there. Anyway, it looks like someone else fixed it already https://github.com/KhronosGroup/OpenGL-Refpages/commit/105a1ad9aaf2e6a865fcac7cc7f3bfe3cd196e17#diff-a7f9ebce64c2d754593efa05af428a62
