### ISSUE TITLE
mismatch on glFramebufferRenderbuffer attachment argument group

### ISSUE THREAD

**Issue by devel0** [KhronosGroup/OpenGL-API#72]
from spec of [glFramebufferRenderbuffer](https://github.com/KhronosGroup/OpenGL-Registry/blob/d11e0a0fcdbda4abb579c7f6ec9fc83e3f2b5fb9/xml/gl.xml#L16964) attachment group is FramebufferAttachment

```xml
<command>
    <proto>void <name>glFramebufferRenderbuffer</name></proto>
    <param group="FramebufferTarget"><ptype>GLenum</ptype> <name>target</name></param>
    <param group="FramebufferAttachment"><ptype>GLenum</ptype> <name>attachment</name></param>
    <param group="RenderbufferTarget"><ptype>GLenum</ptype> <name>renderbuffertarget</name></param>
    <param><ptype>GLuint</ptype> <name>renderbuffer</name></param>
    <glx type="render" opcode="4324"/>
</command>
```

but this haven't [GL_DEPTH_ATTACHMENT](https://github.com/KhronosGroup/OpenGL-Registry/blob/d11e0a0fcdbda4abb579c7f6ec9fc83e3f2b5fb9/xml/gl.xml#L9701) that is referred to a deprecated InvalidateFramebufferAttachment.

```xml
<enum value="0x8D00" name="GL_DEPTH_ATTACHMENT" group="InvalidateFramebufferAttachment"/>
```

But as stated from [current documentation](https://github.com/KhronosGroup/OpenGL-Refpages/blob/master/gl4/glFramebufferRenderbuffer.xml#L129) should included.

I think that `FramebufferAttachment` should used as group in related enum included GL_DEPTH_ATTACHMENT too.

**Comment by pdaniell-nv** [comment]
Would you like to propose a fix for this?

**Comment by devel0** [comment]
Sure PR https://github.com/KhronosGroup/OpenGL-Registry/pull/412

**Comment by pdaniell-nv** [comment]
https://github.com/KhronosGroup/OpenGL-Registry/pull/412 has been merged, closing.
