### ISSUE TITLE
ARB_indirect_parameters documentation error

### ISSUE THREAD

**Issue by CZDanol** [KhronosGroup/OpenGL-API#77]
Hello, I believe you have an error in the https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_indirect_parameters.txt.
In the:

>  The command
> 
>         void MultiDrawArraysIndirectCountARB(enum mode,
>                                              const void *indirect,
>                                              intptr drawcount,
>                                              intptr maxdrawcount,
>                                              sizei stride);

It should be `sizei maxdrawcount`.

**Comment by pdaniell-nv** [comment]
Thanks for spotting this problem and filing the issue. I have created a fix here: https://github.com/KhronosGroup/OpenGL-Registry/pull/441.
