### ISSUE TITLE
add NV_blend_minmax_func to OpenGL registry

### ISSUE THREAD

**Issue by markkilgard** [KhronosGroup/OpenGL-API#8]
Please assign an extension number to the attached NV_blend_minmax_func and add it to the OpenGL and ES registries.
[GL_NV_blend_minmax_factor.txt](https://github.com/KhronosGroup/OpenGL-API/files/1177560/GL_NV_blend_minmax_factor.txt)

**Comment by oddhack** [comment]
OK, done. In the future please submit extensions via PRs to KhronosGroup/OpenGL-Registry (this goes for everyone).
