### ISSUE TITLE
How likely is a new OpenGL version?

### ISSUE THREAD

**Issue by BoyBaykiller** [KhronosGroup/OpenGL-API#87]
How likely is a new OpenGL version?
Are there any official statements on this topic?

**Comment by pdaniell-nv** [comment]
There are no official statements on this question at this time. Are there any features in particular you would like to see in a new core version of OpenGL?

**Comment by BoyBaykiller** [comment]
Ok good to know.

> Are there any features in particular you would like to see in a new core version of OpenGL?

Well there is lots of things. Seeing Ray Tracing, VRS or Mesh Shaders in a core release would be cool of course, but obviously that's unrealistic.

Excluding that kind of stuff my wishlist says:
* add `GL_KHR_shader_subgroup`
* add `GL_ARB_bindless_texture`
* add `GL_ARB_shader_viewport_layer_array`
* add `GL_NV_fragment_shader_barycentric`
* add `GL_NV_shader_buffer_load/store`
* add `GL_EXT_nonuniform_qualifier`
* add `GL_EXT_scalar_block_layout`
* add `GL_EXT_shader_explicit_arithmetic_types`
* remove or deprecate non DSA functions
* remove or deprecate mutable storage for buffers and textures
* remove or deprecate use of non explicit locations or bindings for uniforms, buffer backed blocks, samplers etc.

**Comment by pdaniell-nv** [comment]
Thanks for your feedback. Your request list is a useful data point. I'm going to close this issue, but it will remain archived.
